export enum ErrorCode {
    // default
    INVALID_REQUEST = 'INVALID_REQUEST',
    UNAUTHORIZED = 'UNAUTHORIZED',
    FORBIDDEN = 'FORBIDDEN',
    NOT_FOUND = 'NOT_FOUND',
    INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
    EXTERNAL_API_ERROR = 'EXTERNAL_API_ERROR',
    INVALID_PATH_PARAM = 'INVALID_PATH_PARAM',

    // auth
    POLICY_VERSION_NOT_FOUND = 'POLICY_VERSION_NOT_FOUND',

    // room
    INVALID_ROOM_INPUT = 'INVALID_ROOM_INPUT',
    INVALID_ROOM_REQUEST = 'INVALID_ROOM_REQUEST',
    INVALID_ROOM_STATUS = 'INVALID_ROOM_STATUS',
    INVALID_CANDIDATE = 'INVALID_CANDIDATE',
    ROOM_NOT_FOUND = 'ROOM_NOT_FOUND',
    ROOM_ALREADY_CLOSED = 'ROOM_ALREADY_CLOSED',
    MISSING_ROOM_LIST_TYPE = 'MISSING_ROOM_LIST_TYPE',

    // participant
    NO_SUBMITTED_PARTICIPANTS = 'NO_SUBMITTED_PARTICIPANTS',
    ALREADY_PARTICIPATED = 'ALREADY_PARTICIPATED',
    PARTICIPANT_NOT_FOUND = 'PARTICIPANT_NOT_FOUND',

    // user
    INVALID_NICKNAME = 'INVALID_NICKNAME',
    USER_NOT_FOUND = 'USER_NOT_FOUND',
}
